# Generated by Django 4.0.8 on 2022-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='Название CTE'),
        ),
    ]
